SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[WJbActions]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[WJbActions](
	[Id] [int] IDENTITY(100,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Disabled] [bit] NOT NULL,
	[Type] [nvarchar](255) NOT NULL,
	[MoreJson] [nvarchar](max) NULL,
 CONSTRAINT [PK_WJbActions] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UX_WJbActions_Name] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[WJbHistory]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[WJbHistory](
	[Id] [int] NOT NULL,
	[Priority] [tinyint] NOT NULL,
	[Created] [datetime] NOT NULL,
	[RuleId] [int] NOT NULL,
	[Started] [datetime] NULL,
	[Finished] [datetime] NULL,
	[MoreJson] [nvarchar](max) NULL,
 CONSTRAINT [PK_WJbHistory] PRIMARY KEY CLUSTERED 
(
	[Id] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[WJbQueue]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[WJbQueue](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Priority] [tinyint] NOT NULL,
	[Created] [datetime] NOT NULL,
	[RuleId] [int] NOT NULL,
	[Started] [datetime] NULL,
	[Finished] [datetime] NULL,
	[MoreJson] [nvarchar](max) NULL,
 CONSTRAINT [PK_WJbQueue] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[WJbRules]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[WJbRules](
	[Id] [int] IDENTITY(100,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Disabled] [bit] NOT NULL,
	[Priority] [tinyint] NOT NULL,
	[ActionId] [int] NOT NULL,
	[MoreJson] [nvarchar](max) NULL,
 CONSTRAINT [PK_WJbRules] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[WJbSettings]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[WJbSettings](
	[Name] [nvarchar](50) NOT NULL,
	[Value] [nvarchar](max) NULL,
 CONSTRAINT [PK_WJbSettings] PRIMARY KEY CLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WJbHistory]') AND name = N'IX_WJbHistory_CreatedDesc')
CREATE NONCLUSTERED INDEX [IX_WJbHistory_CreatedDesc] ON [dbo].[WJbHistory]
(
	[Created] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WJbHistory]') AND name = N'IX_WJbHistory_RuleId')
CREATE NONCLUSTERED INDEX [IX_WJbHistory_RuleId] ON [dbo].[WJbHistory]
(
	[RuleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WJbQueue]') AND name = N'IX_WJbQueue_RuleId')
CREATE NONCLUSTERED INDEX [IX_WJbQueue_RuleId] ON [dbo].[WJbQueue]
(
	[RuleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
SET ANSI_PADDING ON

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WJbRules]') AND name = N'UX_WJbRules_Name')
CREATE UNIQUE NONCLUSTERED INDEX [UX_WJbRules_Name] ON [dbo].[WJbRules]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_WJbActions_Disabled]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[WJbActions] ADD  CONSTRAINT [DF_WJbActions_Disabled]  DEFAULT ((0)) FOR [Disabled]
END

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_WJbQueue_Priority]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[WJbQueue] ADD  CONSTRAINT [DF_WJbQueue_Priority]  DEFAULT ((2)) FOR [Priority]
END

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_WJbQueue_Created]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[WJbQueue] ADD  CONSTRAINT [DF_WJbQueue_Created]  DEFAULT (getdate()) FOR [Created]
END

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_WJbRules_Disabled]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[WJbRules] ADD  CONSTRAINT [DF_WJbRules_Disabled]  DEFAULT ((0)) FOR [Disabled]
END

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_WJbRules_Priority]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[WJbRules] ADD  CONSTRAINT [DF_WJbRules_Priority]  DEFAULT ((2)) FOR [Priority]
END

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_WJbRules_WJbActions]') AND parent_object_id = OBJECT_ID(N'[dbo].[WJbRules]'))
ALTER TABLE [dbo].[WJbRules]  WITH CHECK ADD  CONSTRAINT [FK_WJbRules_WJbActions] FOREIGN KEY([ActionId])
REFERENCES [dbo].[WJbActions] ([Id])
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_WJbRules_WJbActions]') AND parent_object_id = OBJECT_ID(N'[dbo].[WJbRules]'))
ALTER TABLE [dbo].[WJbRules] CHECK CONSTRAINT [FK_WJbRules_WJbActions]
